services:
  - type: web
    name: horizon-capital-mic
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn MIC.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"